package io.github.rubenix.yttranscriber.integration.youtube;

import tools.jackson.databind.ObjectMapper;
import io.github.rubenix.yttranscriber.domain.source.VideoMetadata;
import io.github.rubenix.yttranscriber.domain.transcription.TranscriptSegment;
import io.github.rubenix.yttranscriber.exception.ProviderUnavailableException;
import io.github.rubenix.yttranscriber.exception.UnsupportedSourceException;
import io.github.rubenix.yttranscriber.integration.youtube.YtDlpProcessRunner.ProcessResult;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.when;

@ExtendWith(MockitoExtension.class)
class YtDlpSourceProviderTest {

    private static final YtDlpProperties PROPERTIES = new YtDlpProperties("yt-dlp", 30);

    @Mock
    private YtDlpProcessRunner processRunner;

    private YtDlpSourceProvider sourceProvider;

    @BeforeEach
    void setUp() {
        sourceProvider = new YtDlpSourceProvider(processRunner, new ObjectMapper(), PROPERTIES);
    }

    @Test
    void parsesMetadataFromASuccessfulRun() {
        stub("""
                {"id": "dQw4w9WgXcQ", "title": "Never Gonna Give You Up", "duration": 213, "availability": "public", "is_live": false}
                """, 0);

        VideoMetadata metadata = sourceProvider.fetchMetadata("https://www.youtube.com/watch?v=dQw4w9WgXcQ");

        assertThat(metadata.id()).isEqualTo("dQw4w9WgXcQ");
        assertThat(metadata.title()).isEqualTo("Never Gonna Give You Up");
        assertThat(metadata.durationSeconds()).isEqualTo(213);
    }

    @Test
    void rejectsLiveStreams() {
        stub("""
                {"id": "abc", "title": "Live now", "duration": null, "availability": "public", "is_live": true}
                """, 0);

        assertThatThrownBy(() -> sourceProvider.fetchMetadata("https://www.youtube.com/watch?v=abc"))
                .isInstanceOf(UnsupportedSourceException.class);
    }

    @Test
    void rejectsPrivateOrRestrictedVideos() {
        stub("""
                {"id": "abc", "title": "Private", "duration": 100, "availability": "needs_auth", "is_live": false}
                """, 0);

        assertThatThrownBy(() -> sourceProvider.fetchMetadata("https://www.youtube.com/watch?v=abc"))
                .isInstanceOf(UnsupportedSourceException.class);
    }

    @Test
    void rejectsANullAvailabilityWithoutThrowingNullPointerException() {
        stub("""
                {"id": "abc", "title": "Odd video", "duration": 100, "availability": null, "is_live": false}
                """, 0);

        assertThatThrownBy(() -> sourceProvider.fetchMetadata("https://www.youtube.com/watch?v=abc"))
                .isInstanceOf(UnsupportedSourceException.class);
    }

    @Test
    void treatsANonZeroExitCodeAsAnUnsupportedSource() {
        stub("", 1);

        assertThatThrownBy(() -> sourceProvider.fetchMetadata("https://www.youtube.com/watch?v=missing"))
                .isInstanceOf(UnsupportedSourceException.class);
    }

    @Test
    void treatsUnparseableOutputAsProviderUnavailable() {
        stub("not json", 0);

        assertThatThrownBy(() -> sourceProvider.fetchMetadata("https://www.youtube.com/watch?v=abc"))
                .isInstanceOf(ProviderUnavailableException.class);
    }

    private void stub(String stdout, int exitCode) {
        when(processRunner.run(any(), any())).thenReturn(new ProcessResult(exitCode, stdout, ""));
    }

    private static final String SAMPLE_JSON3 = """
            {
              "events": [
                { "segs": [ { "utf8": "" } ] },
                { "tStartMs": 1360, "dDurationMs": 1680, "segs": [ { "utf8": "[music]" } ] },
                { "tStartMs": 18640, "dDurationMs": 3240, "segs": [ { "utf8": "We're no strangers to love" } ] }
              ]
            }
            """;

    @Test
    void parsesSegmentsFromTheManualSubtitleFileWhenAvailable() {
        writeSubtitleFileOnlyFor("--write-subs");

        List<TranscriptSegment> segments = sourceProvider.fetchSegments(
                "https://www.youtube.com/watch?v=dQw4w9WgXcQ", "dQw4w9WgXcQ");

        assertThat(segments).hasSize(2);
        assertThat(segments.get(0)).isEqualTo(new TranscriptSegment(0, 1360, 3040, "[music]"));
        assertThat(segments.get(1)).isEqualTo(new TranscriptSegment(1, 18640, 21880, "We're no strangers to love"));
    }

    @Test
    void fallsBackToAutoGeneratedSubtitlesWhenNoManualTrackExists() {
        writeSubtitleFileOnlyFor("--write-auto-subs");

        List<TranscriptSegment> segments = sourceProvider.fetchSegments(
                "https://www.youtube.com/watch?v=dQw4w9WgXcQ", "dQw4w9WgXcQ");

        assertThat(segments).hasSize(2);
    }

    @Test
    void rejectsVideosWithNoEnglishCaptionsAtAll() {
        when(processRunner.run(any(), any())).thenReturn(new ProcessResult(0, "", ""));

        assertThatThrownBy(() -> sourceProvider.fetchSegments(
                "https://www.youtube.com/watch?v=dQw4w9WgXcQ", "dQw4w9WgXcQ"))
                .isInstanceOf(UnsupportedSourceException.class);
    }

    @Test
    void treatsAFailedAutoSubsAttemptAsProviderUnavailableEvenWhenManualExitedCleanly() {
        // Reproduces a real case: the video has no manual captions (yt-dlp exits 0, no file —
        // a clean "there's nothing here"), but the auto-subs attempt hits an actual failure
        // (e.g. YouTube responding 429 Too Many Requests) rather than cleanly reporting "none".
        // That must NOT be reported as "no captions available" (not retryable) — it's a
        // transient provider problem (retryable).
        when(processRunner.run(any(), any())).thenAnswer(invocation -> {
            List<String> command = invocation.getArgument(0);
            if (command.contains("--write-subs")) {
                return new ProcessResult(0, "", "There are no subtitles for the requested languages");
            }
            return new ProcessResult(1, "", "ERROR: Unable to download video subtitles for 'en': HTTP Error 429: Too Many Requests");
        });

        assertThatThrownBy(() -> sourceProvider.fetchSegments(
                "https://www.youtube.com/watch?v=fLexgOxsZu0", "fLexgOxsZu0"))
                .isInstanceOf(ProviderUnavailableException.class);
    }

    private void writeSubtitleFileOnlyFor(String expectedFlag) {
        when(processRunner.run(any(), any())).thenAnswer(invocation -> {
            List<String> command = invocation.getArgument(0);
            if (command.contains(expectedFlag)) {
                Path dir = Path.of(command.get(command.indexOf("-P") + 1));
                Files.writeString(dir.resolve("dQw4w9WgXcQ.en.json3"), SAMPLE_JSON3);
            }
            return new ProcessResult(0, "", "");
        });
    }
}
